export default {
    SERVER_HOST: process.env.REACT_APP_SERVER_HOST || 'http://localhost:8080/api',

    KAKAO_REST_API_KEY: process.env.REACT_APP_KAKAO_REST_API_KEY,
    KAKAO_REDIRECT_URI: process.env.REACT_APP_KAKAO_REDIRECT_URI,

    GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
    GOOGLE_REDIRECT_URI: process.env.REACT_APP_GOOGLE_REDIRECT_URI
};