export default {
    SERVER_HOST: process.env.REACT_APP_SERVER_HOST,
    SERVER_PORT: process.env.REACT_APP_SERVER_PORT,
    KAKAO_REST_API_KEY: process.env.REACT_APP_KAKAO_REST_API_KEY,
    KAKAO_REDIRECT_URI: process.env.REACT_APP_KAKAO_REDIRECT_URI
};